# Generated by Django 5.2.12 on 2026-06-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_default_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0, help_text='Amount in USD cents'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_label',
            field=models.CharField(blank=True, default='', help_text='1month or 3month', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
