# Generated by Django 5.2.12 on 2026-08-27 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('excerpt', models.TextField(blank=True, help_text='Short teaser shown under the title on the card')),
                ('topic', models.CharField(blank=True, help_text='e.g. Health, Technology, Psychology', max_length=100)),
                ('level', models.CharField(blank=True, choices=[('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced')], max_length=2)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='study/articles/covers/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='study/articles/pdf/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='study.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
