# Generated by Django 5.2.12 on 2026-08-27 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.PositiveSmallIntegerField(choices=[(1, 'Task 1'), (2, 'Task 2')], default=2)),
                ('prompt', models.TextField(help_text='The exam question shown on the card')),
                ('instruction', models.TextField(blank=True, help_text='Line under the prompt, e.g. "Give reasons for your answer and include any relevant examples…"')),
                ('essay', models.TextField(help_text='The full model answer')),
                ('band', models.CharField(default='8.0+', help_text='e.g. 8.0+, 7.5, 9.0', max_length=10)),
                ('is_premium', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingSampleRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='study.writingsample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_sample_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('sample', 'user')},
            },
        ),
    ]
