# Generated by Django 5.2.12 on 2026-08-27 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_writingsample_writingsampleread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, help_text='Speaker or artist', max_length=150)),
                ('audio', models.FileField(upload_to='study/podcasts/audio/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='study/podcasts/covers/')),
                ('duration_sec', models.FloatField(default=0)),
                ('transcript', models.TextField(blank=True)),
                ('words', models.JSONField(blank=True, default=list, help_text='Whisper word timings')),
                ('is_premium', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastListen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_sec', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listens', to='study.podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_listens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('podcast', 'user')},
            },
        ),
    ]
