# Generated by Django 5.2.12 on 2026-08-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_podcast_podcastlisten'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='study/podcasts/video/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='study/podcasts/audio/'),
        ),
    ]
