# Generated by Django 5.2.12 on 2026-08-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_podcast_video_alter_podcast_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='section',
            field=models.CharField(choices=[('shadowing', 'Shadowing'), ('podcast', 'Podcasts')], default='shadowing', max_length=20),
        ),
    ]
