# Generated by Django 5.2.12 on 2026-10-03 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('live', 'Live'), ('soon', 'Tez orada'), ('hidden', 'Yashirin')], default='soon', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('opens', models.PositiveIntegerField(default=0)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['slug', 'date'], name='gameday_slug_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'slug', 'date'), name='uniq_gameday_user_slug_date')],
            },
        ),
    ]
