# Generated by Django 5.2.12 on 2026-05-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='sat_exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
