# Generated by Django 5.2.12 on 2026-05-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_sat_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform',
            field=models.CharField(choices=[('exambridge', 'ExamBridge'), ('testmakon', 'TestMakon')], db_index=True, default='exambridge', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_uid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
