# Generated by Django 5.2.12 on 2026-05-08 18:22

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_platform_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMakonUser',
            fields=[
            ],
            options={
                'verbose_name': 'TestMakon User',
                'verbose_name_plural': 'TestMakon Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
