# Generated by Django 5.2.12 on 2026-05-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_testmakon_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_study_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='user',
            name='email_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='target_band',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
