# Generated by Django 5.2.12 on 2026-03-24 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('GAP', 'Gap Filling'), ('TF', 'True/False'), ('MATCH', 'Matching'), ('ERROR', 'Error Correction'), ('WORD', 'Word Formation')], max_length=10)),
                ('content', models.TextField()),
                ('passage', models.TextField(blank=True, help_text='Reading passage if applicable')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cefr/questions/')),
                ('correct_answer', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CEFRTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], max_length=2)),
                ('test_type', models.CharField(choices=[('FULL', 'Full Practice Test'), ('GRAMMAR', 'Grammar & Vocabulary'), ('READING', 'Reading Comprehension'), ('WRITING', 'Writing')], default='FULL', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('time_limit', models.PositiveSmallIntegerField(default=60, help_text='Minutes')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CEFR Test',
                'ordering': ['level', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CEFRAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score_percent', models.FloatField(blank=True, null=True)),
                ('level_achieved', models.CharField(blank=True, max_length=2)),
                ('tab_switches', models.PositiveSmallIntegerField(default=0)),
                ('security_events', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cefr_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cefr.cefrtest')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CEFRChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cefr.cefrquestion')),
            ],
            options={
                'ordering': ['option'],
            },
        ),
        migrations.AddField(
            model_name='cefrquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cefr.cefrtest'),
        ),
        migrations.CreateModel(
            name='CEFRAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cefr.cefrattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cefr.cefrquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cefrquestion',
            unique_together={('test', 'number')},
        ),
    ]
