# Generated by Django 5.2.12 on 2026-03-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MULTI', 'Multiple Select'), ('GAP', 'Gap Filling'), ('TABLE', 'Table Completion'), ('SHORT', 'Short Answer')], max_length=10)),
                ('content', models.TextField()),
                ('correct_answer', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True)),
                ('group_instruction', models.TextField(blank=True)),
                ('max_selections', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='cefrattempt',
            name='attempt_type',
            field=models.CharField(choices=[('GRAMMAR', 'Grammar/Vocabulary'), ('READING', 'Reading'), ('LISTENING', 'Listening')], default='GRAMMAR', max_length=15),
        ),
        migrations.AddField(
            model_name='cefrattempt',
            name='correct_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cefrattempt',
            name='total_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cefrquestion',
            name='group_instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cefrattempt',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cefr.cefrtest'),
        ),
        migrations.AlterField(
            model_name='cefrtest',
            name='test_type',
            field=models.CharField(choices=[('FULL', 'Full Practice Test'), ('GRAMMAR', 'Grammar & Vocabulary'), ('READING', 'Reading Comprehension'), ('LISTENING', 'Listening'), ('WRITING', 'Writing')], default='FULL', max_length=10),
        ),
        migrations.CreateModel(
            name='CEFRListeningChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=5)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cefr.cefrlisteningquestion')),
            ],
            options={
                'ordering': ['option'],
            },
        ),
        migrations.CreateModel(
            name='CEFRListeningSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(blank=True, upload_to='cefr/audio/')),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('transcript', models.TextField(blank=True, help_text='Full transcript. Use [1], [2] markers for answer positions.')),
                ('is_standalone', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_sections', to='cefr.cefrtest')),
            ],
            options={
                'ordering': ['section_number'],
            },
        ),
        migrations.AddField(
            model_name='cefrlisteningquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cefr.cefrlisteningsection'),
        ),
        migrations.AddField(
            model_name='cefrattempt',
            name='listening_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cefr.cefrlisteningsection'),
        ),
        migrations.CreateModel(
            name='CEFRReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('passage_number', models.PositiveSmallIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cefr/reading/')),
                ('is_standalone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_passages', to='cefr.cefrtest')),
            ],
            options={
                'ordering': ['passage_number'],
            },
        ),
        migrations.AddField(
            model_name='cefrattempt',
            name='reading_passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cefr.cefrreadingpassage'),
        ),
        migrations.CreateModel(
            name='CEFRReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TFNG', 'True/False/Not Given'), ('YNNG', 'Yes/No/Not Given'), ('GAP', 'Gap Filling'), ('MATCH', 'Matching'), ('MULTI', 'Multiple Select'), ('SHORT', 'Short Answer')], max_length=10)),
                ('content', models.TextField()),
                ('correct_answer', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True)),
                ('group_instruction', models.TextField(blank=True)),
                ('max_selections', models.PositiveSmallIntegerField(default=1)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cefr.cefrreadingpassage')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('passage', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CEFRReadingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=5)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cefr.cefrreadingquestion')),
            ],
            options={
                'ordering': ['option'],
            },
        ),
        migrations.CreateModel(
            name='CEFRListeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_answers', to='cefr.cefrattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cefr.cefrlisteningquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='CEFRReadingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_answers', to='cefr.cefrattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cefr.cefrreadingquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
