# Generated by Django 5.2.12 on 2026-03-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr', '0002_add_reading_listening_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cefrlisteningsection',
            options={'ordering': ['level', 'section_number']},
        ),
        migrations.AlterModelOptions(
            name='cefrreadingpassage',
            options={'ordering': ['level', 'passage_number']},
        ),
        migrations.AddField(
            model_name='cefrlisteningsection',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cefrlisteningsection',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='cefrlisteningsection',
            name='time_limit',
            field=models.PositiveSmallIntegerField(default=25, help_text='Minutes'),
        ),
        migrations.AddField(
            model_name='cefrreadingpassage',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=6),
        ),
        migrations.AddField(
            model_name='cefrreadingpassage',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cefrreadingpassage',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cefrreadingpassage',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='cefrreadingpassage',
            name='time_limit',
            field=models.PositiveSmallIntegerField(default=20, help_text='Minutes'),
        ),
        migrations.AlterField(
            model_name='cefrlisteningsection',
            name='is_standalone',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cefrreadingpassage',
            name='is_standalone',
            field=models.BooleanField(default=True),
        ),
    ]
