# Generated by Django 5.2.12 on 2026-04-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr', '0004_reading_listening_question_image_wordbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='cefrreadingquestion',
            name='answer_review',
            field=models.TextField(blank=True, help_text='Passage evidence shown in yellow box during review mode'),
        ),
        migrations.AlterField(
            model_name='cefrlisteningquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MULTI', 'Multiple Select'), ('GAP', 'Gap Filling'), ('TABLE', 'Table / Form Completion'), ('NOTE', 'Notes Completion'), ('FLOW', 'Flowchart Completion'), ('SENT', 'Sentence Completion'), ('MATCH', 'Matching'), ('MFEAT', 'Matching Features'), ('SHORT', 'Short Answer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cefrquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('GAP', 'Gap Filling'), ('TF', 'True/False'), ('MATCH', 'Matching'), ('ERROR', 'Error Correction'), ('WORD', 'Word Formation'), ('TRANS', 'Sentence Transformation')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cefrreadingquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TFNG', 'True/False/Not Given'), ('YNNG', 'Yes/No/Not Given'), ('GAP', 'Gap Filling'), ('MATCH', 'Matching Headings'), ('MINFO', 'Matching Information'), ('MFEAT', 'Matching Features'), ('MEND', 'Matching Sentence Endings'), ('MULTI', 'Multiple Select'), ('TABLE', 'Table Completion'), ('SENT', 'Sentence Completion'), ('SUMM', 'Summary Completion'), ('NOTE', 'Notes / Diagram Completion'), ('FLOW', 'Flowchart Completion'), ('SHORT', 'Short Answer')], max_length=10),
        ),
    ]
