# Generated by Django 5.2.12 on 2026-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr', '0005_add_answer_review_to_cefr_reading_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='cefrlisteningquestion',
            name='answer_review',
            field=models.TextField(blank=True, help_text='Evidence shown in review mode'),
        ),
        migrations.AlterField(
            model_name='cefrlisteningquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MULTI', 'Multiple Select'), ('TFNG', 'True/False/Not Given'), ('YNNG', 'Yes/No/Not Given'), ('GAP', 'Gap Filling'), ('TABLE', 'Table / Form Completion'), ('NOTE', 'Notes Completion'), ('SUMM', 'Summary Completion'), ('FLOW', 'Flowchart Completion'), ('SENT', 'Sentence Completion'), ('MATCH', 'Matching'), ('MFEAT', 'Matching Features'), ('MEND', 'Matching Sentence Endings'), ('SHORT', 'Short Answer')], max_length=10),
        ),
    ]
