# Generated by Django 5.2.12 on 2026-09-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr', '0007_add_image_to_listening_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cefrreadingquestion',
            name='question_type',
            field=models.CharField(choices=[('PGAP', 'Gap in the text'), ('MCQ', 'Multiple Choice'), ('TFNG', 'True/False/Not Given'), ('YNNG', 'Yes/No/Not Given'), ('GAP', 'Gap Filling'), ('MATCH', 'Matching Headings'), ('MINFO', 'Matching Information'), ('MFEAT', 'Matching Features'), ('MEND', 'Matching Sentence Endings'), ('MULTI', 'Multiple Select'), ('TABLE', 'Table Completion'), ('SENT', 'Sentence Completion'), ('SUMM', 'Summary Completion'), ('NOTE', 'Notes / Diagram Completion'), ('FLOW', 'Flowchart Completion'), ('SHORT', 'Short Answer')], max_length=10),
        ),
    ]
