# Generated by Django 5.2.12 on 2026-09-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr', '0009_alter_cefrreadingquestion_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cefrlisteningquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MULTI', 'Multiple Select'), ('TFNG', 'True/False/Not Given'), ('YNNG', 'Yes/No/Not Given'), ('GAP', 'Gap Filling'), ('TABLE', 'Table / Form Completion'), ('NOTE', 'Notes Completion'), ('SUMM', 'Summary Completion'), ('FLOW', 'Flowchart Completion'), ('SENT', 'Sentence Completion'), ('MATCH', 'Matching'), ('MFEAT', 'Matching Features'), ('MEND', 'Matching Sentence Endings'), ('SHORT', 'Short Answer'), ('TMATCH', 'Match speaker to option')], max_length=10),
        ),
    ]
