# Generated by Django 5.2.12 on 2026-09-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr', '0011_link_orphan_listening_mocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cefrtest',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='cefr/audio/'),
        ),
        migrations.AddField(
            model_name='cefrtest',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
