# Generated by Django 5.2.12 on 2026-10-02 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr', '0012_cefrtest_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRWritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('FULL', 'Full test (1.1 + 1.2 + Part 2)'), ('PART1', 'Part 1 (Task 1.1 + 1.2)'), ('PART2', 'Part 2 (essay)')], default='FULL', max_length=5)),
                ('situation', models.TextField(blank=True, help_text='Part 1 context shared by Task 1.1 and 1.2')),
                ('task11', models.TextField(blank=True, help_text='Task 1.1 — informal letter')),
                ('task12', models.TextField(blank=True, help_text='Task 1.2 — formal letter')),
                ('task2', models.TextField(blank=True, help_text='Part 2 — essay')),
                ('time_limit', models.PositiveSmallIntegerField(default=60, help_text='Minutes')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CEFR Writing test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CEFRWritingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict, help_text='{"1.1": text, "1.2": text, "2": text}')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SCORING', 'Being scored'), ('READY', 'Scored'), ('FAILED', 'Scoring failed')], default='IN_PROGRESS', max_length=12)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='0–75 (part tests scaled to 75)', null=True)),
                ('level', models.CharField(blank=True, help_text='C1 / B2 / B1 / BELOW', max_length=8)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cefr_writing_responses', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cefr.cefrwritingtest')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='cefr_cefrwr_user_id_cb544c_idx')],
            },
        ),
    ]
