# Generated by Django 5.2.12 on 2026-10-02 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr', '0013_writing_multilevel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRSpeakingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('part11', models.JSONField(blank=True, default=list, help_text='["question", ...]')),
                ('part12', models.JSONField(blank=True, default=list, help_text='["question", ...] about the two pictures')),
                ('part12_image1', models.ImageField(blank=True, upload_to='cefr/speaking/')),
                ('part12_image2', models.ImageField(blank=True, upload_to='cefr/speaking/')),
                ('part2', models.JSONField(blank=True, default=dict, help_text='{"prompt": "...", "questions": [...]}')),
                ('part2_image', models.ImageField(blank=True, upload_to='cefr/speaking/')),
                ('part3', models.JSONField(blank=True, default=dict, help_text='{"topic": "...", "for": [...], "against": [...]}')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CEFR Speaking test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CEFRSpeakingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=list, help_text='[{"part", "q", "question", "transcript", "audio", "seconds"}]')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SCORING', 'Being scored'), ('READY', 'Scored'), ('FAILED', 'Scoring failed')], default='IN_PROGRESS', max_length=12)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='0–75 (part tests scaled to 75)', null=True)),
                ('level', models.CharField(blank=True, help_text='C1 / B2 / B1 / BELOW', max_length=8)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cefr_speaking_responses', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cefr.cefrspeakingtest')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='cefr_cefrsp_user_id_d10a0b_idx')],
            },
        ),
    ]
