# Generated by Django 5.2.12 on 2026-03-18 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.PositiveSmallIntegerField(choices=[(1, 'Module 1'), (2, 'Module 2')])),
                ('time_limit', models.PositiveSmallIntegerField(default=35)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['module_number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('INPUT', 'Student-Produced Response')], default='MCQ', max_length=10)),
                ('content', models.TextField(help_text='Supports HTML and LaTeX math (\\( \\) for inline, \\[ \\] for block)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('table_data', models.JSONField(blank=True, help_text='Table data as JSON array of rows', null=True)),
                ('passage', models.TextField(blank=True, help_text='Reading passage for English questions')),
                ('correct_answer', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests_app.module')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='choices/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tests_app.question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'ordering': ['option'],
            },
        ),
        migrations.CreateModel(
            name='SavedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='tests_app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Question',
                'verbose_name_plural': 'Saved Questions',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('SAT', 'SAT'), ('PSAT', 'PSAT')], default='SAT', max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('form', models.CharField(default='A', help_text='Form letter: A, B, C, D...', max_length=5)),
                ('is_international', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ['-year', '-month'],
                'unique_together': {('test_type', 'year', 'month', 'form', 'is_international')},
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_question_number', models.PositiveSmallIntegerField(default=1)),
                ('current_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_app.module')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests_app.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Attempt',
                'verbose_name_plural': 'Test Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Seconds spent on this question')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_app.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests_app.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests_app.testattempt')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_score', models.PositiveSmallIntegerField(default=0)),
                ('english_score', models.PositiveSmallIntegerField(default=0)),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('math_raw', models.PositiveSmallIntegerField(default=0)),
                ('english_raw', models.PositiveSmallIntegerField(default=0)),
                ('math_m1_correct', models.PositiveSmallIntegerField(default=0)),
                ('math_m2_correct', models.PositiveSmallIntegerField(default=0)),
                ('english_m1_correct', models.PositiveSmallIntegerField(default=0)),
                ('english_m2_correct', models.PositiveSmallIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tests_app.testattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weak_areas', models.JSONField(default=list)),
                ('strong_areas', models.JSONField(default=list)),
                ('recommendations', models.TextField()),
                ('university_suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='tests_app.testresult')),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
            },
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('ENGLISH', 'Reading & Writing'), ('MATH', 'Math')], max_length=10)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tests_app.test')),
            ],
            options={
                'verbose_name': 'Test Section',
                'verbose_name_plural': 'Test Sections',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tests_app.testsection'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['module', 'number'], name='tests_app_q_module__902d94_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='tests_app_q_difficu_bb421a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('module', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'option')},
        ),
        migrations.AlterUniqueTogether(
            name='savedquestion',
            unique_together={('user', 'question')},
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'status'], name='tests_app_t_user_id_95639c_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test'], name='tests_app_t_user_id_455eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'is_correct'], name='tests_app_a_attempt_8ab133_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'is_bookmarked'], name='tests_app_a_attempt_65027f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['user', 'total_score'], name='tests_app_t_user_id_119da4_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['user', 'calculated_at'], name='tests_app_t_user_id_49644d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testsection',
            unique_together={('test', 'section_type')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('section', 'module_number')},
        ),
    ]
