# Generated by Django 5.2.12 on 2026-03-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Matematika', 'Matematika'), ('Ingliz tili', 'Ingliz tili'), ('Reading', 'Reading & Writing'), ('Boshqa', 'Boshqa')], default='Matematika', max_length=50, verbose_name='Fan')),
                ('topic', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('content', models.TextField(verbose_name='Savol')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bank_questions/', verbose_name='Rasm')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=10, verbose_name='Qiyinlik')),
                ('choice_a', models.TextField(verbose_name='A variant')),
                ('choice_b', models.TextField(verbose_name='B variant')),
                ('choice_c', models.TextField(verbose_name='C variant')),
                ('choice_d', models.TextField(verbose_name='D variant')),
                ('correct_answer', models.CharField(max_length=1, verbose_name="To'g'ri javob")),
                ('explanation', models.TextField(blank=True, verbose_name='Izoh')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yil')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Manba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bank Question',
                'verbose_name_plural': 'Bank Questions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'difficulty'], name='tests_app_b_subject_9484eb_idx'), models.Index(fields=['topic'], name='tests_app_b_topic_5a491c_idx')],
            },
        ),
    ]
