# Generated by Django 5.2.12 on 2026-03-31 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0004_module_difficulty_variant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankquestion',
            new_name='tests_app_b_subject_0c9775_idx',
            old_name='tests_app_b_subject_cat_idx',
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('section', 'module_number', 'difficulty_variant')},
        ),
    ]
