# Generated by Django 5.2.12 on 2026-04-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0005_fix_module_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='is_individual',
            field=models.BooleanField(default=False, help_text='Individual module attempt (not full test)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='difficulty_variant',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('EASY', 'Easy (Adaptive)'), ('MEDIUM', 'Medium (Adaptive)'), ('HARD', 'Hard (Adaptive)')], default='STANDARD', help_text='For Module 2: EASY or HARD variant (adaptive routing)', max_length=10),
        ),
    ]
