# Generated by Django 5.2.12 on 2026-04-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0006_module_medium_variant_individual_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_mode',
            field=models.CharField(choices=[('FULL', 'Full Test (Adaptive)'), ('INDIVIDUAL', 'Individual Module')], default='FULL', help_text='FULL = adaptive M2 (easy/medium/hard), INDIVIDUAL = standard M2 only', max_length=15),
        ),
    ]
