# Generated by Django 5.2.12 on 2026-04-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0007_test_mode_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankquestion',
            name='choice_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='bank_choices/', verbose_name='A rasm'),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='choice_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='bank_choices/', verbose_name='B rasm'),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='choice_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='bank_choices/', verbose_name='C rasm'),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='choice_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='bank_choices/', verbose_name='D rasm'),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='passage',
            field=models.TextField(blank=True, help_text="English savollari uchun o'qish matni, HTML qo'llab-quvvatlanadi", verbose_name='Passage (matn)'),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='table_data',
            field=models.JSONField(blank=True, help_text='[[header1, header2], [row1col1, row1col2], ...]', null=True, verbose_name='Jadval'),
        ),
        migrations.AlterField(
            model_name='bankquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bank_questions/', verbose_name='Savol rasmi'),
        ),
    ]
