# Generated by Django 5.2.12 on 2026-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0010_savedbankquestion_is_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, help_text='SAT content domain category', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, help_text='Sub-topic within the category', max_length=200),
        ),
    ]
