# Generated by Django 5.2.12 on 2026-04-16 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0011_question_category_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('explanation', 'Issue with explanation'), ('wrong_marked', 'Wrong answer marked as correct'), ('explanation_wrong', 'Explanation is incorrect'), ('formatting', 'Formatting/display issue'), ('other', 'Other issue')], default='other', max_length=30)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tests_app.bankquestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Report',
                'verbose_name_plural': 'Question Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
