# Generated by Django 5.2.12 on 2026-10-04 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('SAT', 'SAT')], max_length=3)),
                ('questions', models.JSONField(default=list)),
                ('n', models.PositiveSmallIntegerField(default=0)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('SAT', 'SAT')], max_length=3)),
                ('mode', models.CharField(choices=[('solo', 'solo'), ('duel', 'duel')], default='solo', max_length=5)),
                ('opp_kind', models.CharField(choices=[('ghost', 'ghost'), ('bot', 'bot'), ('duel', 'duel'), ('wait', 'wait')], default='bot', max_length=5)),
                ('opp', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'active'), ('finished', 'finished'), ('abandoned', 'abandoned')], default='active', max_length=10)),
                ('cursor', models.PositiveSmallIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveSmallIntegerField(default=0)),
                ('streak', models.PositiveSmallIntegerField(default=0)),
                ('best_streak', models.PositiveSmallIntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('ranked', models.BooleanField(default=False)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('question_ms', models.PositiveIntegerField(default=7000)),
                ('grace_ms', models.PositiveIntegerField(default=1500)),
                ('srs', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ghost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wordbattle.round')),
                ('qset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='wordbattle.qset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wb_rounds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('level', models.CharField(choices=[('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('SAT', 'SAT')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wb_duels_created', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wb_duels_joined', to=settings.AUTH_USER_MODEL)),
                ('qset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duels', to='wordbattle.qset')),
                ('creator_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wordbattle.round')),
                ('opponent_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wordbattle.round')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveSmallIntegerField()),
                ('word_id', models.PositiveIntegerField()),
                ('qtype', models.CharField(choices=[('en_uz', 'en_uz'), ('uz_en', 'uz_en'), ('syn', 'syn'), ('ant', 'ant'), ('cloze', 'cloze'), ('listen', 'listen')], max_length=6)),
                ('choice', models.SmallIntegerField(blank=True, null=True)),
                ('answered', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False)),
                ('timeout', models.BooleanField(default=False)),
                ('served_at', models.DateTimeField()),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ms', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wordbattle.round')),
            ],
        ),
        migrations.AddIndex(
            model_name='qset',
            index=models.Index(fields=['level', 'created_at'], name='wb_qset_level_created'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['user', 'status'], name='wb_round_user_status'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['level', 'status', 'finished_at'], name='wb_round_level_fin'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['finished_at'], name='wb_round_finished'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='wb_one_active_round'),
        ),
        migrations.AddIndex(
            model_name='duel',
            index=models.Index(fields=['creator', 'created_at'], name='wb_duel_creator'),
        ),
        migrations.AddIndex(
            model_name='duel',
            index=models.Index(fields=['opponent', 'created_at'], name='wb_duel_opponent'),
        ),
        migrations.AddIndex(
            model_name='duel',
            index=models.Index(fields=['created_at'], name='wb_duel_created'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['answered_at'], name='wb_answer_answered'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('round', 'idx'), name='wb_answer_round_idx'),
        ),
    ]
