# Generated by Django 5.2.12 on 2026-10-03 19:39

import django.db.models.deletion
import speaking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, default='A1', max_length=2)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(help_text='The passage the learner reads aloud (one sentence per line is fine).')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position inside its level (smaller first).')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, upload_to=speaking.models.attempt_audio_path)),
                ('mime', models.CharField(blank=True, max_length=60)),
                ('duration_sec', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='PROCESSING', max_length=10)),
                ('error', models.CharField(blank=True, help_text="Why it failed: 'no-speech', 'service', 'bad-audio'", max_length=40)),
                ('transcript', models.TextField(blank=True)),
                ('words', models.JSONField(blank=True, default=list)),
                ('accuracy', models.PositiveSmallIntegerField(default=0)),
                ('fluency_wpm', models.PositiveSmallIntegerField(default=0)),
                ('ok_count', models.PositiveSmallIntegerField(default=0)),
                ('fix_count', models.PositiveSmallIntegerField(default=0)),
                ('skip_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_game_attempts', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='speaking.speakinglesson')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'lesson'], name='speaking_att_user_lesson')],
            },
        ),
    ]
