# Generated by Django 5.2.12 on 2026-03-24 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('test_type', models.CharField(choices=[('ACADEMIC', 'Academic'), ('GENERAL', 'General Training'), ('FULL_MOCK', 'Full Mock Test')], default='ACADEMIC', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IELTS Test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('GAP', 'Gap Filling / Note Completion'), ('MATCH', 'Matching'), ('SHORT', 'Short Answer'), ('MAP', 'Label a Map/Plan')], max_length=10)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ielts/listening/')),
                ('correct_answer', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('part', models.IntegerField(choices=[(1, 'Part 1 — Introduction'), (2, 'Part 2 — Long Turn'), (3, 'Part 3 — Discussion')])),
                ('prompt', models.TextField()),
                ('follow_up_questions', models.JSONField(default=list)),
                ('prep_time', models.PositiveSmallIntegerField(default=60, help_text='Prep time in seconds (Part 2 only)')),
                ('speak_time', models.PositiveSmallIntegerField(default=120, help_text='Speaking time limit in seconds')),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['part', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.IntegerField(choices=[(1, 'Task 1'), (2, 'Task 2 (Essay)')])),
                ('test_type', models.CharField(choices=[('ACADEMIC', 'Academic'), ('GENERAL', 'General Training')], default='ACADEMIC', max_length=10)),
                ('prompt', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Chart/graph for Task 1', null=True, upload_to='ielts/writing/')),
                ('min_words', models.PositiveSmallIntegerField(default=150)),
                ('time_limit', models.PositiveSmallIntegerField(default=20, help_text='Minutes')),
                ('sample_answer', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IELTSAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('reading_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('listening_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('speaking_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('writing_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tab_switches', models.PositiveSmallIntegerField(default=0)),
                ('fullscreen_exits', models.PositiveSmallIntegerField(default=0)),
                ('security_events', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ielts.ieltstest')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='ielts.listeningquestion')),
            ],
            options={
                'ordering': ['option'],
            },
        ),
        migrations.CreateModel(
            name='ListeningSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='ielts/audio/')),
                ('transcript', models.TextField(blank=True)),
                ('is_standalone', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_sections', to='ielts.ieltstest')),
            ],
            options={
                'ordering': ['section_number'],
            },
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ielts.listeningsection'),
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('passage_number', models.PositiveSmallIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ielts/reading/')),
                ('time_limit', models.PositiveSmallIntegerField(default=20, help_text='Minutes')),
                ('is_standalone', models.BooleanField(default=False, help_text='Practice passage (not part of full test)')),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='ielts.ieltstest')),
            ],
            options={
                'ordering': ['passage_number'],
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TFNG', 'True/False/Not Given'), ('YNNG', 'Yes/No/Not Given'), ('GAP', 'Gap Filling'), ('MATCH', 'Matching Headings'), ('SHORT', 'Short Answer'), ('SENT', 'Sentence Completion')], max_length=10)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ielts/questions/')),
                ('correct_answer', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ielts.readingpassage')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('passage', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ReadingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='ielts.readingquestion')),
            ],
            options={
                'ordering': ['option'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='ielts/responses/speaking/')),
                ('transcript', models.TextField(blank=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_responses', to='ielts.ieltsattempt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.speakingtask')),
            ],
        ),
        migrations.CreateModel(
            name='WritingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('word_count', models.PositiveSmallIntegerField(default=0)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ai_criteria', models.JSONField(default=dict, help_text='TA/CC/LR/GRA scores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_responses', to='ielts.ieltsattempt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.writingtask')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_answers', to='ielts.ieltsattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.listeningquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ReadingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_answers', to='ielts.ieltsattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.readingquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
