# Generated by Django 5.2.12 on 2026-03-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0002_add_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningsection',
            name='audio_url',
            field=models.URLField(blank=True, help_text='External audio URL (e.g. from otaboyev-prep.uz)', max_length=500),
        ),
    ]
