# Generated by Django 5.2.12 on 2026-03-28 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0003_add_audio_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltsattempt',
            name='listening_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ielts.listeningsection'),
        ),
        migrations.AddField(
            model_name='ieltsattempt',
            name='reading_passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ielts.readingpassage'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='group_instruction',
            field=models.TextField(blank=True, help_text='e.g. "Questions 22-25: Choose THREE letters A-G"'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='max_selections',
            field=models.PositiveSmallIntegerField(default=1, help_text='For MULTI_SELECT: how many answers student must select'),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='group_instruction',
            field=models.TextField(blank=True, help_text='e.g. "Questions 14-16: Choose THREE answers from A-K"'),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='max_selections',
            field=models.PositiveSmallIntegerField(default=1, help_text='For MULTI_SELECT: how many answers student must select'),
        ),
        migrations.AlterField(
            model_name='listeningchoice',
            name='option',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='content',
            field=models.TextField(help_text='Question/prompt text. For GAP: text with ___ blank. For TABLE: cell label.'),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MULTI', 'Multiple Select (choose N from list)'), ('GAP', 'Gap Filling / Note Completion'), ('TABLE', 'Table / Form / Note Completion'), ('SENT', 'Sentence Completion'), ('MATCH', 'Matching'), ('SHORT', 'Short Answer'), ('MAP', 'Label a Map/Plan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listeningsection',
            name='audio_url',
            field=models.URLField(blank=True, help_text='External audio URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='listeningsection',
            name='transcript',
            field=models.TextField(blank=True, help_text='Full transcript. Use [1], [2] markers to show where answers appear in text.'),
        ),
        migrations.AlterField(
            model_name='readingchoice',
            name='option',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='content',
            field=models.TextField(help_text='Question text. For GAP/TABLE: use ___ for blank. For MATCH: the statement to match.'),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TFNG', 'True/False/Not Given'), ('YNNG', 'Yes/No/Not Given'), ('GAP', 'Gap Filling'), ('MATCH', 'Matching Headings'), ('MINFO', 'Matching Information'), ('SHORT', 'Short Answer'), ('SENT', 'Sentence Completion'), ('MULTI', 'Multiple Select (choose N from list)'), ('TABLE', 'Table / Note / Summary Completion')], max_length=10),
        ),
        migrations.CreateModel(
            name='BookmarkedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('IELTS_READING', 'IELTS Reading'), ('IELTS_LISTENING', 'IELTS Listening'), ('CEFR', 'CEFR')], max_length=20)),
                ('question_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'source_type', 'question_id')},
            },
        ),
    ]
