# Generated by Django 5.2.12 on 2026-03-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0004_add_new_question_types_and_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingtask',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='writingtask',
            name='recommendations',
            field=models.JSONField(blank=True, default=list, help_text='List of vocabulary/tip words shown below the prompt'),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MULTI', 'Multiple Select'), ('GAP', 'Gap Filling'), ('TABLE', 'Table / Form Completion'), ('NOTE', 'Notes Completion'), ('FLOW', 'Flowchart Completion'), ('SENT', 'Sentence Completion'), ('MATCH', 'Matching'), ('MFEAT', 'Matching Features'), ('SHORT', 'Short Answer'), ('MAP', 'Map / Plan Labelling')], max_length=10),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TFNG', 'True/False/Not Given'), ('YNNG', 'Yes/No/Not Given'), ('GAP', 'Gap Filling'), ('MATCH', 'Matching Headings'), ('MINFO', 'Matching Information'), ('MFEAT', 'Matching Features'), ('MEND', 'Matching Sentence Endings'), ('SHORT', 'Short Answer'), ('SENT', 'Sentence Completion'), ('MULTI', 'Multiple Select'), ('TABLE', 'Table Completion'), ('SUMM', 'Summary Completion'), ('NOTE', 'Notes / Diagram Completion'), ('FLOW', 'Flowchart Completion'), ('MAP', 'Diagram / Map Labelling')], max_length=10),
        ),
    ]
