# Generated by Django 5.2.12 on 2026-03-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0005_writing_difficulty_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingresponse',
            name='ai_criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='speakingresponse',
            name='transcripts',
            field=models.JSONField(blank=True, default=list, help_text='[{question, transcript}, ...]'),
        ),
        migrations.AddField(
            model_name='speakingtask',
            name='bullet_points',
            field=models.JSONField(blank=True, default=list, help_text='Bullet points for Part 2 cue card'),
        ),
        migrations.AddField(
            model_name='speakingtask',
            name='follow_up',
            field=models.CharField(blank=True, help_text='Follow-up question after Part 2 long turn', max_length=500),
        ),
        migrations.AddField(
            model_name='speakingtask',
            name='parts_data',
            field=models.JSONField(blank=True, default=list, help_text='Full mock: list of part objects'),
        ),
        migrations.AddField(
            model_name='speakingtask',
            name='questions',
            field=models.JSONField(blank=True, default=list, help_text='List of question strings for Part 1 and Part 3'),
        ),
        migrations.AddField(
            model_name='speakingtask',
            name='test_type',
            field=models.CharField(choices=[('PART', 'Single Part'), ('MOCK', 'Full Mock')], default='PART', max_length=10),
        ),
        migrations.AddField(
            model_name='speakingtask',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='speakingresponse',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='ielts/responses/speaking/'),
        ),
        migrations.AlterField(
            model_name='speakingtask',
            name='part',
            field=models.IntegerField(choices=[(1, 'Part 1 — Introduction'), (2, 'Part 2 — Long Turn'), (3, 'Part 3 — Discussion')], default=1),
        ),
        migrations.AlterField(
            model_name='speakingtask',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
