# Generated by Django 5.2.12 on 2026-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0006_speakingresponse_ai_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='answer_review',
            field=models.TextField(blank=True, help_text='Passage evidence shown in yellow box during review mode'),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='word_bank',
            field=models.JSONField(blank=True, default=list, help_text='Word bank for SUMM type drag-and-drop'),
        ),
    ]
