# Generated by Django 5.2.12 on 2026-04-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0007_add_word_bank_answer_review_to_reading_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='answer_review',
            field=models.TextField(blank=True, help_text='Evidence shown in review mode'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='word_bank',
            field=models.JSONField(blank=True, default=list, help_text='Word bank for SUMM type'),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MULTI', 'Multiple Select'), ('TFNG', 'True/False/Not Given'), ('YNNG', 'Yes/No/Not Given'), ('GAP', 'Gap Filling'), ('TABLE', 'Table / Form Completion'), ('NOTE', 'Notes Completion'), ('SUMM', 'Summary Completion'), ('FLOW', 'Flowchart Completion'), ('SENT', 'Sentence Completion'), ('MATCH', 'Matching'), ('MFEAT', 'Matching Features'), ('MEND', 'Matching Sentence Endings'), ('SHORT', 'Short Answer'), ('MAP', 'Map / Plan Labelling')], max_length=10),
        ),
    ]
