# Generated by Django 5.2.12 on 2026-10-08 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0010_add_speaking_task_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ielts', 'IELTS speaking attempt'), ('cefr', 'CEFR speaking response')], max_length=8)),
                ('ref_id', models.PositiveBigIntegerField(help_text='IELTSAttempt.id or CEFRSpeakingResponse.id')),
                ('task_ref', models.PositiveBigIntegerField(blank=True, help_text='SpeakingTask.id for an IELTS practice attempt (each task is its own test); empty for a full-test attempt and for CEFR', null=True)),
                ('used_at', models.DateTimeField()),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_uses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['user', 'used_at'], name='speaking_use_user_time'), models.Index(fields=['user', 'locked_until'], name='speaking_use_user_lock'), models.Index(fields=['kind', 'ref_id'], name='speaking_use_ref')],
            },
        ),
    ]
