# Generated by Django 5.2.12 on 2026-10-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0011_speaking_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltstest',
            name='is_cambridge',
            field=models.BooleanField(default=False, help_text='Cambridge IELTS material (shown under the Cambridge filter)'),
        ),
        migrations.AddField(
            model_name='listeningsection',
            name='is_cambridge',
            field=models.BooleanField(default=False, help_text='Cambridge IELTS material (shown under the Cambridge filter)'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='is_cambridge',
            field=models.BooleanField(default=False, help_text='Cambridge IELTS material (shown under the Cambridge filter)'),
        ),
    ]
