# Generated by Django 5.2.12 on 2026-08-20 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(blank=True, help_text='e.g. Travel, Movies, Daily life', max_length=100)),
                ('level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced')], default='B1', max_length=2)),
                ('body', models.TextField(help_text='The passage the learner reads aloud')),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ShadowingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='games/shadowing/')),
                ('duration_sec', models.FloatField(default=0)),
                ('transcript', models.TextField(blank=True, help_text='What Whisper heard')),
                ('word_results', models.JSONField(blank=True, default=list, help_text='[{word, status, score}, ...]')),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('accuracy_pct', models.PositiveSmallIntegerField(default=0)),
                ('fluency_wpm', models.PositiveSmallIntegerField(default=0)),
                ('cefr_estimate', models.CharField(blank=True, max_length=2)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('flagged_count', models.PositiveSmallIntegerField(default=0)),
                ('skipped_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadowing_attempts', to=settings.AUTH_USER_MODEL)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.shadowingtext')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
