# Generated by Django 5.2.12 on 2026-10-03 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('tobys-day', "Toby's Day"), ('voice-drive', 'Voice Drive')], max_length=40)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Free-form state the game stores (≤ 20 KB)')),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('stars_total', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_game_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice game progress',
                'verbose_name_plural': 'Voice game progress',
                'constraints': [models.UniqueConstraint(fields=('user', 'slug'), name='uniq_voice_progress_user_slug')],
            },
        ),
        migrations.CreateModel(
            name='VoiceGameRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('tobys-day', "Toby's Day"), ('voice-drive', 'Voice Drive')], max_length=40)),
                ('score', models.PositiveIntegerField(default=0)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('level', models.CharField(blank=True, default='', max_length=40)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('lines_said', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_game_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug', 'created_at'], name='voice_run_slug_created_idx')],
            },
        ),
    ]
