# Generated by Django 5.2.12 on 2026-03-18 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/')),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('min_total_score', models.PositiveSmallIntegerField(default=0, help_text='Minimum total SAT score')),
                ('min_math_score', models.PositiveSmallIntegerField(default=0)),
                ('min_english_score', models.PositiveSmallIntegerField(default=0)),
                ('acceptance_rate', models.FloatField(default=0.0, help_text='Acceptance rate in percent (e.g. 5.4)')),
                ('ranking', models.PositiveSmallIntegerField(blank=True, help_text='National ranking', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['ranking', 'name'],
                'indexes': [models.Index(fields=['min_total_score'], name='universitie_min_tot_6f66a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='UniversityRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score_used', models.PositiveSmallIntegerField()),
                ('math_score_used', models.PositiveSmallIntegerField()),
                ('english_score_used', models.PositiveSmallIntegerField()),
                ('chance', models.CharField(blank=True, help_text='reach / match / safety', max_length=20)),
                ('ai_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_recs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University Recommendation',
                'verbose_name_plural': 'University Recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
