# Generated by Django 5.2.12 on 2026-06-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centermembership',
            name='member_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
